### ISSUE TITLE
[Question] `midich:` example method not implemented

### ISSUE THREAD

**Issue by labordep** [lucretiomsp/PharoLiveCoding#14]
Hi,

I'm trying to test the example describe on the home page, but `midich:` is a non implemented method: 

`16 semiquavers to: #hats; midich: 7`

What is the equivalent now ?

Thanks :)

**Comment by lucretiomsp** [comment]
sorry for the confusion and thankf for let me know bout it,
there are two ways of setting the midiChannel, depending on if you are using the PerformerSuperDirt or PerformerMIDI.

if you using the PerformerMIDI
```Smalltalk
16 semiquavers to: #hats; midiChannel: 7
```

if you using the PerformerSuperDirt
```Smalltalk
16 semiquavers to: #hats; midiChan: 7
```

I will fix the documentation tomorrow and I will provide more example. also, in the future there could be the possibility to use both messages for both Performers.

**Comment by labordep** [comment]
Thanks :-)
